---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      GOOGLE_APIKEY: ${GOOGLE_API_KEY}
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-palm'
      ENABLE_MODULES: 'text2vec-palm,generative-palm'
      CLUSTER_HOSTNAME: 'node1'

  postgres:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
        - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8880:8080

volumes:
  weaviate_data:
  pg_data:
