[project]
name = "rag"
version = "0.1.0"
description = ""
authors = [
    {name = "GlockPL", email = "pakerzus@tlen.pl"}
]
requires-python = ">=3.11"
dependencies = [
    "langchain-weaviate>=0.0.8",
    "pydantic[email]>=2.10.6",
    "pydantic-settings>=2.7.1",
    "weaviate-client>=4.23",
    "langchain-google-genai>=4.4",
    "langgraph>=1.2",
    "langchain-openai>=1.6",
    "langgraph-checkpoint-postgres>=3.1",
    "fastapi>=0.142",
    "uvicorn>=0.34.0",
    "python-jose>=3.4.0",
    "python-multipart>=0.0.20",
    "redis>=5.2.1",
    "json-repair>=0.39.1",
    "natsort>=8.4.0",
    "google-genai>=1.5.0",
    "mistralai>=1.5.1",
    "PyMuPDF>=1.25.3",
    "bcrypt>=4.3.0",
    "slowapi>=0.1.9",
    "asyncpg>=0.30.0",
    "python-dotenv>=1.1.1",
    "tqdm>=4.67.1",
    "sqlalchemy>=2.0.43",
    "langchain-core>=1.6",
    "psycopg[binary,pool]>=3.2",
]

[dependency-groups]
dev = [
    "pytest>=5.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
